"""Human review queue for person mentions (#5): only real ambiguity, with its evidence."""

from __future__ import annotations

from collections import defaultdict
from pathlib import Path

import yaml

from ..models.enums import MentionResolutionStatus

HEADER = (
    "Generated by `szocatlas build`; do not edit. Each entry is a person mention that has at least "
    "one candidate Person but not enough evidence (or contradicting evidence) for an automatic "
    "decision. Mentions without any candidate are not listed (see the quality report). To decide, "
    "add to review/manual_overrides.yaml:\n"
    "  mention_decisions:\n"
    "    - {mention_id: pmn_..., person_id: per_..., decision: same_as | not_same_as,\n"
    "       reviewer: <name>, date: YYYY-MM-DD, evidence: \"...\"}\n"
    "Use source_ref instead of mention_id to decide every page of one source record."
)


def write_mention_review(ds, path: Path) -> int:
    persons = {p.canonical_id: p for p in ds.entities.values() if p.entity_type.value == "Person"}
    label = {e.canonical_id: e.label for e in ds.entities.values()}
    groups: dict[str, list[dict]] = defaultdict(list)
    for m in sorted(ds.mentions.values(), key=lambda m: (m.stated_name, m.source_url)):
        if m.resolution.status is not MentionResolutionStatus.REVIEW_REQUIRED:
            continue
        top = next((c.person_id for c in m.candidates if not c.rejected), None)
        groups[top or ""].append({
            "mention_id": m.canonical_id,
            "stated_name": m.stated_name,
            "page": m.source_url,
            **({"linked_profile": m.linked_profile_url} if m.linked_profile_url else {}),
            **({"stated_profile_urls": m.stated_profile_urls} if m.stated_profile_urls else {}),
            "context": [
                {"relation": c.relation.value, **({"role": c.qualifiers["role"]} if c.qualifiers.get("role") else {}),
                 "target": label.get(c.target_id, c.target_id) if c.target_id else c.target_ref,
                 "snippet": c.snippet}
                for c in m.context],
            "why_not_automatic": m.resolution.reason,
            "candidates": [
                {"person_id": c.person_id, "label": persons[c.person_id].label if c.person_id in persons else None,
                 "name_match": c.name_match, "positive": c.signals, "negative": c.negative_signals,
                 **({"rejected": True} if c.rejected else {})}
                for c in m.candidates],
        })
    payload = {
        "_comment": HEADER,
        "summary": {"mentions_to_review": sum(len(v) for v in groups.values()),
                    "candidate_persons": len([k for k in groups if k])},
        "by_candidate": [
            {"person_id": pid, "label": persons[pid].label if pid in persons else None, "mentions": items}
            for pid, items in sorted(groups.items(), key=lambda kv: (-len(kv[1]), kv[0]))
        ],
    }
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(yaml.safe_dump(payload, allow_unicode=True, sort_keys=False, width=110), encoding="utf-8")
    return payload["summary"]["mentions_to_review"]
